### ISSUE TITLE
Bug: version 1.0.3 이후로 알고리즘 풀이 업데이트가 안되는 이슈

### ISSUE THREAD

**Issue by Duhoon** [Coplit-To-Github/CoplitToGithub#6]
1.0.3 버전으로 업데이트 한 이후
CoplitToGithub를 이용하여 git repository에 커밋을 할 때,
새로 파일을 생성하는 것까진 정상적으로 작동합니다.
하지만 알고리즘 수정이후 다시 커밋을 하면
해당 요청에 대해서는 git repository 에 반영이 안되는 것 같습니다.

확인 부탁드립니다.

**Comment by Duhoon** [comment]
이 문제가 해결되면
commit message 기능과 합쳐서 1.0.4로 배포하면 될 것 같습니다.
현재는 버전업을 안 한 상태입니다.

**Comment by seolcoding** [comment]
아마 기본 repo visibility를 private로 바꾸는 과정에서 생긴 에러로 생각되는데 확인해보겠습니다.
기본적인 유닛 테스트가 없으니 새로운 기능을 추가할때마다 생기는 버그에 손수 대응해야하니 비효율적이네요.
다시한번 이미 구현된 기능에 대해서 기본적인 테스트를 작성하는게 신규 기능개발보다 우선시 되어야겠다 생각합니다.

**Comment by Duhoon** [comment]
이번 사례를 겪어보니 저도 깊게 공감됩니다.
저도 테스트 코드 작성하는 부분을 같이 살펴보도록 하겠습니다.

**Comment by seolcoding** [comment]
이슈 해결했습니다. 

프라이빗 리포와 파일을 조회시 accessToken을 api에 전달해줘야되는데 예전 api는 그걸 인자로 넣어주지 않아서 발생한 오류였습니다.
곧 manifest.json 수정해서 v1.0.4까지 배포해보겠습니다.

처음에 말씀드렸던 것 처럼 브랜칭 정책도 관리하고싶은데, 아직은 능력이 안되는구요..
차차 개선해봅시다.
